-- =============================================================
-- MOONVIEW MEDICAL HMS — RLS DISABLE & PUBLIC SELECT POLICY SCRIPT
-- Execute this script in the Supabase SQL Editor if needed
-- =============================================================

ALTER TABLE IF EXISTS public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.patient DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.doctor DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.registrar DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.lab_technician DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pharmacist DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.schedule DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.appointment DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.consultations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.vitals_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.prescriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.lab_catalog DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.lab_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.lab_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.lab_samples DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.lab_inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.medicine DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.procurement_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.procurement_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pharmacy_sale DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pharmacy_sale_item DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.password_change_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.system_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.treatment_bundles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.pricing_matrix DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.icd10 DISABLE ROW LEVEL SECURITY;

GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
